### ISSUE TITLE
A little too much repetition in your css

### ISSUE THREAD

**Issue by farishkash** [chrisgrazioli/prj-rev-bwfs-dasmoto#1]
Main item I noticed is 

`font-weight: bold;`

you could have reduce the css you wrote and even remove the bold class if you just typed

```
h1, h2, span {

font-weight: bold;

}
```

**Comment by chrisgrazioli** [comment]
`html{
  font-family: Helvetica, sans-serif;
}
h1,h2,span{
  font-weight: bold;
}
h1{
  font-size: 100px;
  color:khaki;
  text-align: center;
  background-image: url(https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg);
}
h2{
  font-size:32px
  color:white;
}
.green{
  background-color: mediumspringgreen;
}
.red{
  background-color: lightcoral;
}
.skyblue{
  background-color: skyblue;
}
.blue{
  color:blue;
  }
`

**Comment by chrisgrazioli** [comment]
So I took out the repetitive bolding and the class selector, and added a css rule for h1,h2,span
