### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [chrisgrazioli/prj-rev-bwfs-dasmoto#2]
Overall Excellent project.  When I look review this one I look for two things.  The use of divs and no repetition in css.

You were near perfect and that is ok that your css was a little repetitive, you will get into the habit of avoiding this with experience.

Reduce the repetition as suggested then as a challenge take a look at bootstrap, http://getbootstrap.com/ .  Think about or even try to add this into your website and experiment with it to make it mobile friendly.  It will also help you prepare for some more advance concepts.

**Comment by chrisgrazioli** [comment]
Okay. I think I can add download or link to bootstrap easy enough.
Once bootstrap has been added, I just have to go through my classes and exchange them with the standard bootstrap class names correct?
